using System;
using System.Diagnostics;

//Auto generated by Tebas project manager
class Cerium{
	public static int Main(string[] args){
		if(args.Length != 1){
			Console.Error.WriteLine("Expected 1 argument: config path");
			return 1;
		}
		
		if(!File.Exists(args[0])){
			Console.Error.WriteLine("'" + args[0] + "' does not exist. Please provide a valid config path");
			return 2;
		}
		
		try{
			Config config = Config.Parse(args[0]);
			Resolved res = config.Resolve();
			string fa = res.getFfmpegArgs();
			
			string ffmpegPath = config.GetFFMPEGPath();
			
			ProcessStartInfo psi = new ProcessStartInfo{
				FileName = ffmpegPath,
				Arguments = fa,
				UseShellExecute = false,
				RedirectStandardOutput = false,
				RedirectStandardError = false,
				CreateNoWindow = false //allows it to print directly in the current terminal
			};
			
			using Process process = Process.Start(psi);
			process.WaitForExit();
			
			int xc = process.ExitCode;
			Console.WriteLine("FFmpeg finished with code " + xc);
			
			res.cleanup();
			
			return xc == 0 ? 0 : 4;
		}catch(Exception e){
			Console.Error.WriteLine(e);
			return 3;
		}
	}
}